version: "3.9"

services:

  wsl:
    build: .
    image: khs1994/wsl:latest

  wsl-php-builder-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.0}
        - OS_TYPE=debian:buster-slim
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.0}-debian-buster_amd64

  wsl-php-builder-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.27}
        - OS_TYPE=debian:buster-slim
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.27}-debian-buster_amd64

  wsl-php-builder-80:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_80:-8.0.14}
        - OS_TYPE=debian:buster-slim
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php80_${PHP_VERSION_80:-8.0.14}-debian-buster_amd64

  wsl-php-builder-nightly:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=nightly
        - OS_TYPE=debian:buster-slim
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php82_0.0.0-debian-buster_amd64

# latest stable php and debian
  wsl-php-builder-debian11-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.0}
        - OS_TYPE=debian:bullseye-slim
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.0}-debian-bullseye_amd64

  wsl-php-builder-ubuntu1804-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.0}
        - OS_TYPE=ubuntu:18.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.0}-ubuntu-bionic_amd64

  wsl-php-builder-ubuntu1804-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.27}
        - OS_TYPE=ubuntu:18.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.27}-ubuntu-bionic_amd64

  wsl-php-builder-ubuntu1804-80:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_80:-8.0.14}
        - OS_TYPE=ubuntu:18.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php80_${PHP_VERSION_80:-8.0.14}-ubuntu-bionic_amd64

  wsl-php-builder-ubuntu2004-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.27}
        - OS_TYPE=ubuntu:20.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.27}-ubuntu-focal_amd64

  wsl-php-builder-ubuntu2004-80:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_80:-8.0.14}
        - OS_TYPE=ubuntu:20.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php80_${PHP_VERSION_80:-8.0.14}-ubuntu-focal_amd64

  wsl-php-builder-ubuntu2004-nightly:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=nightly
        - OS_TYPE=ubuntu:20.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php82_0.0.0-ubuntu-focal_amd64

# latest stable php and ubuntu
  wsl-php-builder-ubuntu2110-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.0}
        - OS_TYPE=ubuntu:21.10
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.0}-ubuntu-impish_amd64

  wsl-php-builder-rhel7-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.27}
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.27}-centos-7_amd64

  wsl-php-builder-rhel8-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.0}
        - OS_TYPE=quay.io/centos/centos:stream8
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.0}-centos-8_amd64

  wsl-php-builder-rhel8-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.27}
        - OS_TYPE=quay.io/centos/centos:stream8
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.27}-centos-8_amd64

# latest stable php and rhel
  wsl-php-builder-rhel8-80:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_80:-8.0.14}
        - OS_TYPE=quay.io/centos/centos:stream8
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php80_${PHP_VERSION_80:-8.0.14}-centos-8_amd64

  wsl-php-builder-rhel9-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.0}
        - OS_TYPE=quay.io/centos/centos:stream9
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.0}-centos-9_amd64

  wsl-php-builder-rocky8-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.0}
        - OS_TYPE=rockylinux:8
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.0}-rocky-8_amd64

  wsl-php-builder-fc35-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.0}
        - OS_TYPE=fedora:35
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.0}-fedora-35_amd64

  wsl-php-builder-fc35-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.27}
        - OS_TYPE=fedora:35
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.27}-fedora-35_amd64

  wsl-php-builder-fc35-80:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_80:-8.0.14}
        - OS_TYPE=fedora:35
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php80_8.0.14-fedora-35_amd64

  wsl-php-builder-fc35-nightly:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=nightly
        - OS_TYPE=fedora:35
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php82_0.0.0-fedora-35_amd64

# latest php and fedora
  wsl-php-builder-fc36-nightly:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=nightly
        - OS_TYPE=fedora:36
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php82_0.0.0-fedora-36_amd64
