version: "3.9"

services:

  wsl:
    build: .
    image: khs1994/wsl:latest

# https://endoflife.software/operating-systems/linux/debian
  wsl-php-builder-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.30}
        - OS_TYPE=debian:buster-slim
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.30}-debian-buster_amd64

  wsl-php-builder-80:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_80:-8.0.18}
        - OS_TYPE=debian:buster-slim
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php80_${PHP_VERSION_80:-8.0.18}-debian-buster_amd64

  wsl-php-builder-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.4}
        - OS_TYPE=debian:buster-slim
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.4}-debian-buster_amd64

  wsl-php-builder-nightly:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=nightly
        - OS_TYPE=debian:buster-slim
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php82_0.0.0-debian-buster_amd64

# latest stable php and debian
  wsl-php-builder-debian11-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.4}
        - OS_TYPE=debian:bullseye-slim
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.4}-debian-bullseye_amd64

# https://endoflife.software/operating-systems/linux/ubuntu
  wsl-php-builder-ubuntu1804-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.30}
        - OS_TYPE=ubuntu:18.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.30}-ubuntu-bionic_amd64

  wsl-php-builder-ubuntu1804-80:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_80:-8.0.18}
        - OS_TYPE=ubuntu:18.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php80_${PHP_VERSION_80:-8.0.18}-ubuntu-bionic_amd64

  wsl-php-builder-ubuntu1804-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.4}
        - OS_TYPE=ubuntu:18.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.4}-ubuntu-bionic_amd64

  wsl-php-builder-ubuntu2004-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.30}
        - OS_TYPE=ubuntu:20.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.30}-ubuntu-focal_amd64

  wsl-php-builder-ubuntu2004-80:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_80:-8.0.18}
        - OS_TYPE=ubuntu:20.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php80_${PHP_VERSION_80:-8.0.18}-ubuntu-focal_amd64

  wsl-php-builder-ubuntu2004-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.4}
        - OS_TYPE=ubuntu:20.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.4}-ubuntu-focal_amd64

  wsl-php-builder-ubuntu2204-nightly:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=nightly
        - OS_TYPE=ubuntu:22.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php82_0.0.0-ubuntu-jammy_amd64

# latest stable php and ubuntu
  wsl-php-builder-ubuntu2204-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.4}
        - OS_TYPE=ubuntu:22.04
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.4}-ubuntu-jammy_amd64

# rhel

  wsl-php-builder-rhel7-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.30}
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.30}-centos-7_amd64

  wsl-php-builder-rhel8-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.30}
        - OS_TYPE=quay.io/centos/centos:stream8
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.30}-centos-8_amd64

  wsl-php-builder-rhel8-80:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_80:-8.0.18}
        - OS_TYPE=quay.io/centos/centos:stream8
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php80_${PHP_VERSION_80:-8.0.18}-centos-8_amd64

  wsl-php-builder-rhel8-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.4}
        - OS_TYPE=quay.io/centos/centos:stream8
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.4}-centos-8_amd64

  wsl-php-builder-rhel9-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.4}
        - OS_TYPE=quay.io/centos/centos:stream9
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.4}-centos-9_amd64

# https://github.com/docker-library/docs/tree/master/rockylinux

  wsl-php-builder-rocky8-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.4}
        - OS_TYPE=rockylinux:8
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.4}-rocky-8_amd64

  wsl-php-builder-rocky9-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.4}
        - OS_TYPE=rockylinux:9
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.4}-rocky-9_amd64

# fedora
# https://github.com/docker-library/docs/tree/master/fedora

  wsl-php-builder-fc35-74:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_74:-7.4.30}
        - OS_TYPE=fedora:35
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php74_${PHP_VERSION_74:-7.4.30}-fedora-35_amd64

  wsl-php-builder-fc35-80:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_80:-8.0.18}
        - OS_TYPE=fedora:35
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php80_${PHP_VERSION_80:-8.0.18}-fedora-35_amd64

  wsl-php-builder-fc36-81:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION_81:-8.1.4}
        - OS_TYPE=fedora:36
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php81_${PHP_VERSION_81:-8.1.4}-fedora-36_amd64

  wsl-php-builder-fc36-nightly:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=nightly
        - OS_TYPE=fedora:36
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php82_0.0.0-fedora-36_amd64

# latest php and fedora
  wsl-php-builder-fc37-nightly:
    build:
      context: .
      dockerfile: wsl.phpbuilder.rhel.Dockerfile
      args:
        - PHP_VERSION=nightly
        - OS_TYPE=fedora:37
    image: ${registry:-docker.io}/khs1994/wsl:khs1994-wsl-php82_0.0.0-fedora-37_amd64
